# Generated by Django 4.2.4 on 2023-09-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
